In [1]:
from scipy.stats import randint, uniform

In [2]:
ri = randint(0, 10) # 0~9 무작위 수
ri.rvs(10) # 0~9사이 숫자 중 무작위 수를 11개 생성

array([9, 8, 9, 7, 8, 2, 2, 5, 0, 1])

In [7]:
import numpy as np
np.unique(ri.rvs(1000), return_counts=True) # 중복된 총 갯수를 함께 반환

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([109, 105, 100,  93, 100,  94,  89, 109, 110,  91]))

In [8]:
ui = uniform(0,1) # 0~1 사이의 무작위 실수
ui.rvs(5) # 0~1 사이의 무작위 실수를 5개 생성

array([0.45255692, 0.24269664, 0.2082458 , 0.30617541, 0.60139746])